site_name: Python Development Best Practices 2025
theme:
  name: material
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Ethos: ethos.md
  - Security Practices: security.md
  - Environment Management: environment.md
  - Code Style & Formatting: style.md
  - Modern Python Syntax: syntax.md
  - Application Design: design.md
  - Testing: testing.md
  - Data Validation: validation.md
  - Logging & Observability: logging.md
  - Containerization: containerization.md
  - API Development: api.md
  - Background Tasks: tasks.md
  - Data Persistence: persistence.md
  - AI & Data Science: ai.md
  - Edge-Case Pitfalls: pitfalls.md
  - References: references.md