site_name: Python Development Best Practices 2025

# Repository information
repo_url: https://github.com/pedroanisio/py_dev_guide_2025
repo_name: pedroanisio/py_dev_guide_2025
edit_uri: edit/main/docs/

# Theme configuration
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true
  - tags
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

# Markdown extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.smartsymbols

# Navigation structure
nav:
  - Home: index.md
  - Fundamentals:
    - Our Ethos: ethos.md
    - Security Practices: security.md
    - Environment Management: environment.md
    - Code Style & Formatting: style.md
    - Modern Python Syntax: syntax.md
  - Architecture & Design:
    - Application Design: design.md
    - Testing: testing.md
    - Data Validation: validation.md
    - Logging & Observability: logging.md
  - Infrastructure & Deployment:
    - Containerization: containerization.md
    - API Development: api.md
    - Background Tasks: tasks.md
    - Data Persistence: persistence.md
  - Advanced Topics:
    - AI & Data Science: ai.md
    - Edge-Case Pitfalls: pitfalls.md
  - Resources:
    - References: references.md
    - Glossary: glossary.md

# Extra configurations
extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation.